version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: spark-postgres
    environment:
      POSTGRES_DB: spark
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - spark_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d spark" ]
      interval: 5s
      timeout: 5s
      retries: 20

  redis:
    image: redis:7
    container_name: spark-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - spark_redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  spark_pg_data:
  spark_redis_data:
